//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiboMarket.Models
{
    using System;

    public partial class usuario
    {
        public int idUser { get; set; }
        public string C_User { get; set; }
        public string nombre { get; set; }
        public string lastname { get; set; }
        public string pass { get; set; }
        public string NumTelefono { get; set; }
    }
}
