name: CI on Push and Pull Request

on: [push]

jobs:
  Practice:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what in there
      run: |
        ls
    - name: Show what it's inside
      run: |
        cd ..
        ls
  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        cd SqlitePractica
        nuget restore
        cd SqlitePractica.Android
        msbuild SqlitePractica.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
  iOS:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS
      run: |
        cd SqlitePractica
        nuget restore
        msbuild SqlitePractica.iOS/SqlitePractica.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
